# Generated by Django 5.1.2 on 2024-11-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="platformaccess",
            old_name="payment_date",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="platformaccess",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
