# Generated by Django 5.1.2 on 2024-10-13 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MDA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=400, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="mda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.mda",
            ),
        ),
    ]
