# Generated by Django 5.1.2 on 2024-10-13 12:02

from django.db import migrations


def add_mdas(apps, schema_editor):
    MDA = apps.get_model("users", "MDA")
    mda = [
        "National Agency for the Prohibition of Trafficking in Persons(NAPTIP)",
        "Nigerian Police Force (NPF)",
        "Federal Ministry of Trade and Investment",
        "Federal Ministry of Interior",
        "National Agricultural Seeds Council",
        "Federal Ministry of Finance",
        "Federal Ministry of Agriculture",
        "Federal Road Safety Corps",
        "Federal Ministry of Education",
        "Nigeria Customs Service",
    ]
    for mda_name in mda:
        MDA.objects.create(name=mda_name)


def remove_mdas(apps, schema_editor):
    MDA = apps.get_model("users", "MDA")
    MDA.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_mda_alter_customuser_mda"),
    ]

    operations = [
        migrations.RunPython(add_mdas, remove_mdas),
    ]
