# Generated by Django 5.1.2 on 2025-01-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_populate_mdas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
