# Generated by Django 5.1.2 on 2024-10-16 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useranswer",
            name="selected_choice",
        ),
        migrations.RemoveField(
            model_name="question",
            name="questioon_type",
        ),
        migrations.AddField(
            model_name="question",
            name="choice_a",
            field=models.CharField(default="N/A", max_length=255),
        ),
        migrations.AddField(
            model_name="question",
            name="choice_b",
            field=models.CharField(default="N/A", max_length=255),
        ),
        migrations.AddField(
            model_name="question",
            name="choice_c",
            field=models.CharField(default="N/A", max_length=255),
        ),
        migrations.AddField(
            model_name="question",
            name="choice_d",
            field=models.CharField(default="N/A", max_length=255),
        ),
        migrations.AddField(
            model_name="question",
            name="correct_key",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                default="A",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="selected_key",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                default="A",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="exams.exam",
            ),
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
    ]
