# Generated by Django 5.1.2 on 2024-10-19 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0002_remove_useranswer_selected_choice_and_more"),
        ("users", "0004_populate_mdas"),
    ]

    operations = [
        migrations.AddField(
            model_name="examcategory",
            name="mda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_categories",
                to="users.mda",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="choice_a",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="question",
            name="choice_b",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="question",
            name="choice_c",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="question",
            name="choice_d",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="examcategory",
            unique_together={("name", "mda")},
        ),
    ]
