# Generated by Django 5.1.2 on 2024-10-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0003_examcategory_mda_alter_question_choice_a_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examcategory",
            name="name",
            field=models.CharField(max_length=400),
        ),
    ]
