# Generated by Django 5.1.2 on 2024-10-21 22:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0004_alter_examcategory_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userexam",
            name="score",
            field=models.FloatField(default=0),
        ),
        migrations.AddConstraint(
            model_name="userexam",
            constraint=models.UniqueConstraint(
                condition=models.Q(("end_time__isnull", True)),
                fields=("user", "exam"),
                name="unique_active_exam",
            ),
        ),
    ]
