# Generated by Django 5.1.2 on 2024-10-21 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0005_alter_userexam_score_userexam_unique_active_exam"),
    ]

    operations = [
        migrations.AddField(
            model_name="useranswer",
            name="user_exam",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_answers",
                to="exams.userexam",
            ),
        ),
    ]
