# Generated by Django 5.1.2 on 2024-10-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0006_useranswer_user_exam"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userexam",
            name="unique_active_exam",
        ),
        migrations.AddField(
            model_name="exam",
            name="question_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userexam",
            name="attempt",
            field=models.IntegerField(default=1),
        ),
    ]
