# Generated by Django 5.1.2 on 2024-10-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0007_remove_userexam_unique_active_exam_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="randomized_question_order",
            field=models.JSONField(default=list),
        ),
    ]
