# Generated by Django 5.1.2 on 2024-11-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0008_exam_randomized_question_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="randomized_question_order",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
