# Generated by Django 5.1.2 on 2025-01-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0009_alter_exam_randomized_question_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="choice_e",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="question",
            name="correct_key",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D"), ("E", "E")],
                default="A",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="selected_key",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D"), ("E", "E")],
                default="A",
                max_length=1,
            ),
        ),
    ]
