# Generated by Django 5.1.2 on 2025-01-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0010_question_choice_e_alter_question_correct_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userexam",
            name="randomized_questions",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
