# Generated by Django 5.1.2 on 2025-01-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0011_userexam_randomized_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="userexam",
            name="question_order",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="userexam",
            name="selected_questions",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
