
# Submit answers
POST http://127.0.0.1:8000/exams/submit-answer/
Authorization: Token 237669bd2a523ca28bf19ece2c6ba78a973845f7
Content-Type: application/json

{
    "exam": 4,
    "question": 8,
    "selected_key": "A"
}